#pragma once
// =============================================================================
// GcodeExporter.h  —  G-code Export Pipeline (IR-based)
// =============================================================================
//
// Architecture overview:
//
//   GcodeExporter::buildIR()
//     └─ Converts SliceResult geometry into GcodeIR::Program
//        (pure geometry + extrusion math, no post-processing)
//
//   GcodeExporter::buildDefaultPipeline()
//     └─ Creates PostProcessPipeline with default passes:
//          TimingAnnotPass → RetractPass → WipePass → CoolingPass →
//          FanControlPass → ArcFitPass → PressureAdvPass → ProgressAnnotPass
//
//   GcodeExporter::exportToString()
//     └─ buildIR() → pipeline.run() → GcodeSerializer::serialize()
//
// Users can customize the pipeline:
//   auto prog = GcodeExporter::buildIR(result);
//   auto pipe = GcodeExporter::buildDefaultPipeline(params);
//   pipe.getPass("ArcFitPass")->enabled = false;  // disable arc fitting
//   pipe.run(prog);
//   auto gcode = GcodeIR::GcodeSerializer().serialize(prog);
//
// =============================================================================

#include "GcodeIR.h"
#include "GcodeIRPasses.h"
#include "SlicerEngine.h"
#include "DualExtruder.h"
#include "ToolChangePass.h"
#include <sstream>
#include <fstream>
#include <iomanip>
#include <cmath>

class GcodeExporter {
public:
    // =========================================================================
    // GcodeMove — for visualization (parsed from final G-code)
    // pathType: 0=travel, 1=outer_shell, 2=infill, 3=solid, 4=support,
    //           5=skirt, 6=raft, 7=bridge, 8=support_interface, 9=inner_shell
    // =========================================================================
    struct GcodeMove {
        glm::vec3 from, to;
        float     extrusion;
        int       layerIdx;
        bool      isTravel;
        int       pathType;
        bool      isArc;
        glm::vec2 arcCenter;
        bool      arcCCW;
    };

    // =========================================================================
    // Stage 1: Build IR from SliceResult
    // =========================================================================
    static GcodeIR::Program buildIR(const SliceResult& result,
                                     const std::string& printerName = "Generic FDM")
    {
        GcodeIR::Program prog;
        if (!result.success || result.layers.empty()) return prog;

        const SlicerParams& p = result.params;
        prog.printerName  = printerName;
        prog.totalLayers  = (int)result.layers.size();
        prog.layerStats.resize(prog.totalLayers);
        prog.reserve(result.layers.size() * 512);

        // ---- Header comments ----
        prog.push(GcodeIR::Instruction::raw(
            "; Generated by MCUT Boolean Viewer — Slicer Module (IR Pipeline)"));
        prog.push(GcodeIR::Instruction::raw(
            "; Printer     : " + printerName));
        prog.push(GcodeIR::Instruction::raw(
            "; Layers      : " + std::to_string(result.layers.size())));
        {
            std::ostringstream h;
            h << std::fixed << std::setprecision(2);
            h << "; Layer H     : " << p.layerHeight << " mm";
            prog.push(GcodeIR::Instruction::raw(h.str()));
            h.str(""); h << "; Nozzle      : " << p.nozzleDiameter << " mm";
            prog.push(GcodeIR::Instruction::raw(h.str()));
            h.str(""); h << "; Infill      : " << (int)(p.infillDensity*100) << "%";
            prog.push(GcodeIR::Instruction::raw(h.str()));
            h.str(""); h << "; Shells      : " << p.numShells;
            prog.push(GcodeIR::Instruction::raw(h.str()));
        }
        prog.push(GcodeIR::Instruction::raw(";"));

        // ---- Startup sequence ----
        prog.push(GcodeIR::Instruction::raw("G28                    ; Home all axes"));
        prog.push(GcodeIR::Instruction::raw("G90                    ; Absolute positioning"));
        prog.push(GcodeIR::Instruction::raw("M82                    ; Absolute extrusion"));
        prog.push(GcodeIR::Instruction::setTemp((int)p.extruderTemp, false, false));
        prog.push(GcodeIR::Instruction::setTemp((int)p.bedTemp,      true,  false));
        prog.push(GcodeIR::Instruction::setTemp((int)p.extruderTemp, false, true));
        prog.push(GcodeIR::Instruction::setTemp((int)p.bedTemp,      true,  true));
        prog.push(GcodeIR::Instruction::setFan(0));
        prog.push(GcodeIR::Instruction::resetE());
        prog.push(GcodeIR::Instruction::raw("; --- Purge line ---"));
        prog.push(GcodeIR::Instruction::raw("G1 Z0.3 F3000"));
        prog.push(GcodeIR::Instruction::raw("G1 X10 Y10 F5000"));
        prog.push(GcodeIR::Instruction::raw("G1 X100 Y10 E10 F1500"));
        prog.push(GcodeIR::Instruction::resetE());
        prog.push(GcodeIR::Instruction::raw(";"));

        // Extrusion math
        float nozzleArea   = (float)M_PI * (p.nozzleDiameter  * 0.5f) * (p.nozzleDiameter  * 0.5f);
        float filamentArea = (float)M_PI * (p.filamentDiameter * 0.5f) * (p.filamentDiameter * 0.5f);

        auto extPerMm = [&](float lh, float ew) -> float {
            return (filamentArea > 1e-8f) ? (ew * lh / filamentArea) : 0.0f;
        };

        float E = 0.0f;
        float curX = 0, curY = 0, curZ = -999.0f;

        // Helper: emit a travel move (no extrusion)
        auto emitTravel = [&](float x, float y, float z, float feedMmS,
                               GcodeIR::GcodeFeature feat = GcodeIR::GcodeFeature::Travel)
        {
            // Insert synthetic Retract before travel
            prog.push(GcodeIR::Instruction::retract());

            auto ins = GcodeIR::Instruction::moveLinear(x, y, z, feedMmS, 0, E, true, feat);
            ins.pos.hasZ = (std::abs(z - curZ) > 1e-4f);
            prog.push(ins);

            // Insert synthetic Unretract after travel
            prog.push(GcodeIR::Instruction::unretract());

            curX = x; curY = y;
            if (ins.pos.hasZ) curZ = z;
        };

        // Helper: emit extrusion move
        auto emitExtrude = [&](float x, float y, float z,
                                float feedMmS, float lh, float ew,
                                GcodeIR::GcodeFeature feat)
        {
            float dx = x - curX, dy = y - curY;
            float segLen = std::sqrt(dx*dx + dy*dy);
            if (segLen < 1e-4f) return;

            float em = extPerMm(lh, ew);
            float dE = segLen * em;
            E += dE;

            auto ins = GcodeIR::Instruction::moveLinear(x, y, z, feedMmS, dE, E, false, feat);
            ins.pos.hasZ = (std::abs(z - curZ) > 1e-4f);
            prog.push(ins);

            curX = x; curY = y;
            if (ins.pos.hasZ) curZ = z;
        };

        // Helper: emit a loop (closed polygon)
        auto emitLoop = [&](const Loop2& loop, float feedMmS,
                             float lh, float ew,
                             GcodeIR::GcodeFeature feat)
        {
            if (loop.size() < 2) return;
            emitTravel(loop[0].x, loop[0].y, curZ, p.travelSpeed, GcodeIR::GcodeFeature::Travel);
            for (size_t i = 1; i <= loop.size(); ++i)
                emitExtrude(loop[i % loop.size()].x, loop[i % loop.size()].y,
                            curZ, feedMmS, lh, ew, feat);
        };

        // Helper: emit open paths
        auto emitPaths = [&](const std::vector<Path2>& paths, float feedMmS,
                              float lh, float ew,
                              GcodeIR::GcodeFeature feat)
        {
            for (auto& path : paths) {
                if (path.size() < 2) continue;
                emitTravel(path[0].x, path[0].y, curZ, p.travelSpeed, GcodeIR::GcodeFeature::Travel);
                for (size_t i = 1; i < path.size(); ++i)
                    emitExtrude(path[i].x, path[i].y, curZ, feedMmS, lh, ew, feat);
            }
        };

        // ---- Layers ----
        for (auto& layer : result.layers) {
            float lh = (layer.index == 0) ? p.firstLayerHeight : p.layerHeight;

            // Layer change marker
            prog.push(GcodeIR::Instruction::layerChange(layer.index, layer.z, lh));

            if (layer.isRaftLayer) {
                bool isBase = (layer.index < p.raftBaseLayers);
                float raftSpd = isBase ? p.raftBaseSpeed : p.raftInterfaceSpeed;
                float raftEW  = p.extrusionWidth * 1.5f;

                prog.push(GcodeIR::Instruction::featureBegin(GcodeIR::GcodeFeature::Raft));
                for (auto& loop : layer.skirtLoops)
                    emitLoop(loop, raftSpd, lh, raftEW, GcodeIR::GcodeFeature::Raft);
                emitPaths(layer.raftPaths, raftSpd, lh, raftEW, GcodeIR::GcodeFeature::Raft);
                prog.push(GcodeIR::Instruction::featureEnd(GcodeIR::GcodeFeature::Raft));
                continue;
            }

            float firstMult = (layer.index == 0) ? 1.0f : 1.0f;
            float outerSpd  = (layer.index == 0) ? p.firstLayerSpeed : p.outerPerimSpeed;
            float innerSpd  = (layer.index == 0) ? p.firstLayerSpeed : p.innerPerimSpeed;
            float infillSpd = (layer.index == 0) ? p.firstLayerSpeed : p.infillSpeed;

            // Print order: Skirt → Support → SupportIface → InnerShells →
            //              OuterShell → Solid → Bridge → Infill

            // 1. Skirt
            if (!layer.skirtLoops.empty()) {
                prog.push(GcodeIR::Instruction::featureBegin(GcodeIR::GcodeFeature::Skirt));
                for (auto& loop : layer.skirtLoops)
                    emitLoop(loop, outerSpd * 0.9f, lh, p.extrusionWidth, GcodeIR::GcodeFeature::Skirt);
                prog.push(GcodeIR::Instruction::featureEnd(GcodeIR::GcodeFeature::Skirt));
            }

            // 2. Support
            if (!layer.supportPaths.empty()) {
                prog.push(GcodeIR::Instruction::featureBegin(GcodeIR::GcodeFeature::Support));
                emitPaths(layer.supportPaths, p.supportSpeed, lh, p.extrusionWidth, GcodeIR::GcodeFeature::Support);
                prog.push(GcodeIR::Instruction::featureEnd(GcodeIR::GcodeFeature::Support));
            }

            // 3. Support interface
            if (!layer.supportInterfacePaths.empty()) {
                prog.push(GcodeIR::Instruction::featureBegin(GcodeIR::GcodeFeature::SupportIface));
                emitPaths(layer.supportInterfacePaths, p.supportSpeed * 0.8f, lh,
                          p.extrusionWidth * 0.9f, GcodeIR::GcodeFeature::SupportIface);
                prog.push(GcodeIR::Instruction::featureEnd(GcodeIR::GcodeFeature::SupportIface));
            }

            // 4. Inner shells (inner → outer)
            for (int s = (int)layer.shells.size()-1; s >= 1; --s) {
                prog.push(GcodeIR::Instruction::featureBegin(GcodeIR::GcodeFeature::InnerShell));
                for (auto& loop : layer.shells[s])
                    emitLoop(loop, innerSpd, lh, p.extrusionWidth, GcodeIR::GcodeFeature::InnerShell);
                prog.push(GcodeIR::Instruction::featureEnd(GcodeIR::GcodeFeature::InnerShell));
            }

            // 5. Outer shell
            if (!layer.shells.empty()) {
                prog.push(GcodeIR::Instruction::featureBegin(GcodeIR::GcodeFeature::OuterShell));
                for (auto& loop : layer.shells[0])
                    emitLoop(loop, outerSpd, lh, p.outerExtrusionWidth, GcodeIR::GcodeFeature::OuterShell);
                prog.push(GcodeIR::Instruction::featureEnd(GcodeIR::GcodeFeature::OuterShell));
            }

            // 6. Solid fill
            if (!layer.solidPaths.empty()) {
                prog.push(GcodeIR::Instruction::featureBegin(GcodeIR::GcodeFeature::Solid));
                emitPaths(layer.solidPaths, infillSpd, lh, p.extrusionWidth, GcodeIR::GcodeFeature::Solid);
                prog.push(GcodeIR::Instruction::featureEnd(GcodeIR::GcodeFeature::Solid));
            }

            // 7. Bridge fill
            if (!layer.bridgePaths.empty()) {
                prog.push(GcodeIR::Instruction::featureBegin(GcodeIR::GcodeFeature::Bridge));
                emitPaths(layer.bridgePaths, p.bridgeSpeed, lh, p.extrusionWidth * 1.1f, GcodeIR::GcodeFeature::Bridge);
                prog.push(GcodeIR::Instruction::featureEnd(GcodeIR::GcodeFeature::Bridge));
            }

            // 8. Infill
            if (!layer.infillPaths.empty()) {
                prog.push(GcodeIR::Instruction::featureBegin(GcodeIR::GcodeFeature::Infill));
                emitPaths(layer.infillPaths, infillSpd, lh, p.extrusionWidth, GcodeIR::GcodeFeature::Infill);
                prog.push(GcodeIR::Instruction::featureEnd(GcodeIR::GcodeFeature::Infill));
            }

            // 9. Prime tower (dual extruder — injected by DualExtruderPlanner)
            if (!layer.primeTowerPaths.empty()) {
                prog.push(GcodeIR::Instruction::featureBegin(GcodeIR::GcodeFeature::Purge));
                emitPaths(layer.primeTowerPaths, 60.0f, lh, p.extrusionWidth, GcodeIR::GcodeFeature::Purge);
                prog.push(GcodeIR::Instruction::featureEnd(GcodeIR::GcodeFeature::Purge));
            }
        }

        // ---- End sequence ----
        prog.push(GcodeIR::Instruction::raw("\n; --- End of print ---"));
        {
            std::ostringstream h;
            h << std::fixed << std::setprecision(3);
            h << "G1 Z" << (result.meshMax.z + 10.0f) << " F3000  ; Lift nozzle";
            prog.push(GcodeIR::Instruction::raw(h.str()));
            h.str(""); h << "G1 X0 Y" << (result.meshMax.y + 20.0f) << " F5000  ; Present print";
            prog.push(GcodeIR::Instruction::raw(h.str()));
        }
        prog.push(GcodeIR::Instruction::setFan(0));
        prog.push(GcodeIR::Instruction::setTemp(0, false, false));
        prog.push(GcodeIR::Instruction::setTemp(0, true,  false));
        prog.push(GcodeIR::Instruction::raw("M84                    ; Motors off"));

        prog.totalFilament = result.estimatedFilament;
        return prog;
    }

    // =========================================================================
    // Stage 2: Build default post-processing pipeline from SlicerParams
    // =========================================================================
    // Overload with dual extruder support
    static GcodeIR::PostProcessPipeline buildDefaultPipeline(
        const SlicerParams& p,
        const DualExtruderParams* dualParams = nullptr,
        const std::vector<LayerExtruderAssignment>* assignments = nullptr)
    {
        GcodeIR::PostProcessPipeline pipe;

        // Pass 1: Timing annotation (needed by CoolingPass and FanControlPass)
        pipe.addPass<GcodeIR::TimingAnnotPass>();

        // Pass 2: Retraction
        GcodeIR::RetractPass::Config retractCfg;
        retractCfg.retractionLength    = p.retractionLength;
        retractCfg.retractionSpeed     = p.retractionSpeed;
        retractCfg.unretractSpeed      = p.retractionSpeed;
        retractCfg.minTravelForRetract = p.minTravelForRetract;
        retractCfg.enableZHop          = p.enableZHop;
        retractCfg.zHopHeight          = p.zHopHeight;
        retractCfg.filamentDiameter    = p.filamentDiameter;
        pipe.addPass<GcodeIR::RetractPass>(retractCfg);

        // Pass 3: Wipe before retract
        GcodeIR::WipePass::Config wipeCfg;
        wipeCfg.enabled      = p.enableWipe;
        wipeCfg.wipeDistance = p.wipeDistance;
        pipe.addPass<GcodeIR::WipePass>(wipeCfg);

        // Pass 4: Cooling (slow down for minimum layer time)
        GcodeIR::CoolingPass::Config coolingCfg;
        coolingCfg.minLayerTime    = p.minLayerTime;
        coolingCfg.fanMaxLayerTime = p.fanMaxLayerTime;
        coolingCfg.minPrintSpeed   = p.minPrintSpeed;
        coolingCfg.slowDownEnabled = p.enableCoolingSlowdown;
        pipe.addPass<GcodeIR::CoolingPass>(coolingCfg);

        // Pass 5: Fan control
        GcodeIR::FanControlPass::Config fanCfg;
        fanCfg.firstFanLayer    = p.firstFanLayer;
        fanCfg.minFanSpeed      = p.minFanSpeed;
        fanCfg.maxFanSpeed      = p.maxFanSpeed;
        fanCfg.bridgeFanSpeed   = p.bridgeFanSpeed;
        fanCfg.fanMaxLayerTime  = p.fanMaxLayerTime;
        fanCfg.fanMinLayerTime  = p.minLayerTime;
        pipe.addPass<GcodeIR::FanControlPass>(fanCfg);

        // Pass 6: Arc fitting (G2/G3)
        GcodeIR::ArcFitPass::Config arcCfg;
        arcCfg.enabled   = p.enableArcFitting;
        arcCfg.tolerance = p.arcTolerance;
        pipe.addPass<GcodeIR::ArcFitPass>(arcCfg);

        // Pass 7: Pressure advance
        GcodeIR::PressureAdvPass::Config paCfg;
        paCfg.enabled      = p.enablePressureAdvance;
        paCfg.outerShellPA = p.paOuterShell;
        paCfg.innerShellPA = p.paInnerShell;
        paCfg.infillPA     = p.paInfill;
        paCfg.bridgePA     = 0.0f;
        paCfg.useKlipper   = p.paUseKlipper;
        pipe.addPass<GcodeIR::PressureAdvPass>(paCfg);

        // Pass 8: Progress annotation (M73)
        pipe.addPass<GcodeIR::ProgressAnnotPass>();

        // Pass 9 (optional): Tool change for dual extruder
        // Inserted BEFORE TimingAnnotPass so timing reflects actual tool change moves.
        // In practice we insert it at the front of the pipeline.
        if (dualParams && dualParams->enabled && assignments) {
            GcodeIR::ToolChangePass::Config tcCfg;
            tcCfg.enabled    = true;
            tcCfg.dualParams = *dualParams;
            tcCfg.assignments= *assignments;
            // Insert at front (before timing pass) so all downstream passes see T0/T1 context
            pipe.insertPassFront<GcodeIR::ToolChangePass>(tcCfg);

            // Extruder context propagation (after tool change)
            pipe.insertPassAt<GcodeIR::ExtruderContextPass>(1);
        }

        return pipe;
    }

    // =========================================================================
    // Convenience: full pipeline export to string
    // =========================================================================
    static std::string exportToString(const SliceResult& result,
                                       const std::string& printerName = "Generic FDM",
                                       const DualExtruderParams* dualParams = nullptr)
    {
        if (!result.success || result.layers.empty())
            return "; Empty slice result\n";

        // Stage 1: Build IR
        auto prog = buildIR(result, printerName);

        // Stage 2: Plan dual extruder assignments (if enabled)
        std::vector<LayerExtruderAssignment> assignments;
        if (dualParams && dualParams->enabled) {
            assignments = DualExtruderPlanner::plan(result, *dualParams);
        }

        // Stage 3: Run post-processing pipeline
        auto pipe = buildDefaultPipeline(
            result.params,
            (dualParams && dualParams->enabled) ? dualParams : nullptr,
            assignments.empty() ? nullptr : &assignments);
        pipe.run(prog);

        // Stage 4: Serialize
        GcodeIR::GcodeSerializer serializer;
        serializer.cfg.emitComments    = true;
        serializer.cfg.emitFeatureTags = true;
        return serializer.serialize(prog);
    }

    // Export to file
    static bool exportToFile(const SliceResult& result,
                              const std::string& filepath,
                              const std::string& printerName = "Generic FDM")
    {
        std::string gcode = exportToString(result, printerName);
        std::ofstream f(filepath);
        if (!f.is_open()) return false;
        f << gcode;
        return true;
    }

    // =========================================================================
    // Parse final G-code string back into 3D moves for visualization
    // Handles G0/G1 linear and G2/G3 arc commands.
    // =========================================================================
    static std::vector<GcodeMove> parseForVisualization(const std::string& gcode)
    {
        std::vector<GcodeMove> moves;
        moves.reserve(8192);

        float x = 0, y = 0, z = 0, e = 0;
        float prevX = 0, prevY = 0, prevZ = 0, prevE = 0;
        int   layerIdx = -1;
        float lastZ = -1.0f;
        int   curPathType = 1;

        std::istringstream ss(gcode);
        std::string line;
        while (std::getline(ss, line)) {
            if (line.empty()) continue;

            if (line[0] == ';') {
                if (line.find("Layer") != std::string::npos ||
                    line.find("Raft")  != std::string::npos) {
                    ++layerIdx; curPathType = 1;
                }
                if      (line.find("Skirt")             != std::string::npos) curPathType = 5;
                else if (line.find("Support Interface")  != std::string::npos) curPathType = 8;
                else if (line.find("Support")            != std::string::npos) curPathType = 4;
                else if (line.find("Outer Shell")        != std::string::npos) curPathType = 1;
                else if (line.find("Inner Shell")        != std::string::npos) curPathType = 9;
                else if (line.find("Solid Fill")         != std::string::npos) curPathType = 3;
                else if (line.find("Bridge")             != std::string::npos) curPathType = 7;
                else if (line.find("Infill")             != std::string::npos) curPathType = 2;
                else if (line.find("Raft")               != std::string::npos) curPathType = 6;
                continue;
            }

            auto cpos = line.find(';');
            if (cpos != std::string::npos) line = line.substr(0, cpos);

            if (line.rfind("G1", 0) == 0 || line.rfind("G0", 0) == 0) {
                auto getVal = [&](char c) {
                    auto pos = line.find(c);
                    if (pos == std::string::npos) return;
                    try {
                        float v = std::stof(line.substr(pos+1));
                        if      (c == 'X') x = v;
                        else if (c == 'Y') y = v;
                        else if (c == 'Z') z = v;
                        else if (c == 'E') e = v;
                    } catch(...) {}
                };
                getVal('X'); getVal('Y'); getVal('Z'); getVal('E');
                if (z != lastZ) { ++layerIdx; lastZ = z; }

                float dE = e - prevE;
                GcodeMove mv;
                mv.from      = glm::vec3(prevX, prevY, prevZ);
                mv.to        = glm::vec3(x, y, z);
                mv.extrusion = dE;
                mv.layerIdx  = std::max(0, layerIdx);
                mv.isTravel  = (dE <= 0.0f);
                mv.pathType  = mv.isTravel ? 0 : curPathType;
                mv.isArc     = false;
                mv.arcCCW    = false;

                if (glm::distance(mv.from, mv.to) > 1e-4f) moves.push_back(mv);
                prevX = x; prevY = y; prevZ = z; prevE = e;
            }
            else if (line.rfind("G2", 0) == 0 || line.rfind("G3", 0) == 0) {
                bool ccw = (line[1] == '3');
                float ex = x, ey = y;
                float I = 0, J = 0;
                auto getVal2 = [&](char c) {
                    auto pos = line.find(c);
                    if (pos == std::string::npos) return;
                    try {
                        float v = std::stof(line.substr(pos+1));
                        if      (c == 'X') ex = v;
                        else if (c == 'Y') ey = v;
                        else if (c == 'I') I  = v;
                        else if (c == 'J') J  = v;
                        else if (c == 'E') e  = v;
                    } catch(...) {}
                };
                getVal2('X'); getVal2('Y'); getVal2('I'); getVal2('J'); getVal2('E');

                float cx = x + I, cy = y + J;
                float r  = std::sqrt(I*I + J*J);
                float startA = std::atan2(y - cy, x - cx);
                float endA   = std::atan2(ey - cy, ex - cx);
                float dA = endA - startA;
                if (ccw && dA < 0) dA += 2*(float)M_PI;
                if (!ccw && dA > 0) dA -= 2*(float)M_PI;

                int segs = std::max(4, (int)(std::abs(r * dA) / 0.5f));
                float dE = e - prevE;
                float dePerSeg = dE / segs;

                for (int si = 1; si <= segs; ++si) {
                    float a = startA + dA * si / segs;
                    float nx = cx + r * std::cos(a);
                    float ny = cy + r * std::sin(a);

                    GcodeMove mv;
                    mv.from      = glm::vec3(prevX, prevY, prevZ);
                    mv.to        = glm::vec3(nx, ny, z);
                    mv.extrusion = dePerSeg;
                    mv.layerIdx  = std::max(0, layerIdx);
                    mv.isTravel  = (dE <= 0.0f);
                    mv.pathType  = mv.isTravel ? 0 : curPathType;
                    mv.isArc     = true;
                    mv.arcCenter = glm::vec2(cx, cy);
                    mv.arcCCW    = ccw;

                    if (glm::distance(mv.from, mv.to) > 1e-4f) moves.push_back(mv);
                    prevX = nx; prevY = ny;
                }
                x = ex; y = ey; prevE = e;
            }
            else if (line.rfind("G92", 0) == 0) {
                auto pos = line.find('E');
                if (pos != std::string::npos) {
                    try { e = std::stof(line.substr(pos+1)); prevE = e; } catch(...) {}
                }
            }
        }
        return moves;
    }
};
