#pragma once
// =============================================================================
// GcodeExporter.h  —  FDM G-code Generator
// =============================================================================
// Converts SliceResult into RepRap-compatible G-code (Marlin / Klipper / Prusa).
//
// G-code structure:
//   ; --- Raft Base Layer N ---      (raft layers before model)
//   ; --- Layer N (z=X.XXX mm) ---   (model layers)
//   ; Skirt                          (skirt loops, first layer)
//   ; Support                        (support grid)
//   ; Shell N                        (perimeter shells)
//   ; Solid / Infill                 (fill paths)
//
// Extrusion amount E:
//   dE = (path_length × nozzle_area × layer_height) / filament_area
//
// GcodeMove.pathType encodes semantic feature for colored visualization:
//   0 = travel, 1 = shell, 2 = infill, 3 = solid,
//   4 = support, 5 = skirt, 6 = raft
// =============================================================================

#include "SlicerEngine.h"
#include <sstream>
#include <fstream>
#include <iomanip>
#include <cmath>

class GcodeExporter {
public:
    // =========================================================================
    // Export to string (for in-memory preview)
    // =========================================================================
    static std::string exportToString(const SliceResult& result,
                                       const std::string& printerName = "Generic FDM")
    {
        if (!result.success || result.layers.empty())
            return "; Empty slice result\n";

        std::ostringstream ss;
        ss << std::fixed << std::setprecision(4);

        const SlicerParams& p = result.params;

        // ---- Header ----
        ss << "; Generated by MCUT Boolean Viewer — Slicer Module\n";
        ss << "; Printer  : " << printerName << "\n";
        ss << "; Layers   : " << result.layers.size() << "\n";
        ss << "; Layer H  : " << p.layerHeight << " mm\n";
        ss << "; Nozzle   : " << p.nozzleDiameter << " mm\n";
        ss << "; Infill   : " << (int)(p.infillDensity * 100) << "%\n";
        ss << "; Shells   : " << p.numShells << "\n";
        ss << "; Skirt    : " << (p.enableSkirt ? std::to_string(p.skirtLoopCount) + " loops" : "disabled") << "\n";
        ss << "; Raft     : " << (p.enableRaft  ? std::to_string(p.raftBaseLayers + p.raftInterfaceLayers) + " layers" : "disabled") << "\n";
        ss << "; Support  : " << (p.enableSupport ? std::to_string((int)p.supportAngle) + "deg threshold" : "disabled") << "\n";
        ss << "; Filament : " << std::setprecision(1) << result.estimatedFilament << " mm\n";
        ss << "; Est.Time : " << (int)(result.estimatedTime/60) << "m "
                               << (int)result.estimatedTime%60 << "s\n";
        ss << ";\n";

        // ---- Startup sequence ----
        ss << "G28                    ; Home all axes\n";
        ss << "G90                    ; Absolute positioning\n";
        ss << "M82                    ; Absolute extrusion\n";
        ss << "M104 S" << (int)p.extruderTemp << "           ; Set extruder temp\n";
        ss << "M140 S" << (int)p.bedTemp      << "            ; Set bed temp\n";
        ss << "M109 S" << (int)p.extruderTemp << "           ; Wait for extruder\n";
        ss << "M190 S" << (int)p.bedTemp      << "            ; Wait for bed\n";
        ss << "G92 E0                 ; Reset extruder\n";
        ss << "; --- Purge line ---\n";
        ss << "G1 Z0.3 F3000\n";
        ss << "G1 X10 Y10 F5000\n";
        ss << "G1 X100 Y10 E10 F1500\n";
        ss << "G92 E0\n";
        ss << ";\n";

        // Precompute extrusion cross-sections
        float nozzleArea   = (float)M_PI * (p.nozzleDiameter  * 0.5f) * (p.nozzleDiameter  * 0.5f);
        float filamentArea = (float)M_PI * (p.filamentDiameter * 0.5f) * (p.filamentDiameter * 0.5f);
        float extrusionMult = (filamentArea > 0.0f) ? (nozzleArea * p.layerHeight / filamentArea) : 0.0f;

        float E = 0.0f;
        float curX = 0.0f, curY = 0.0f, curZ = -999.0f;
        bool  retracted = false;

        auto mmPerMin = [](float mmPerSec) { return mmPerSec * 60.0f; };

        // Helper: travel to point (with retraction management)
        auto travelTo = [&](Vec2 pt, float travelSpd) {
            if (retracted) {
                E += p.retractionLength;
                ss << "G1 E" << E << " F" << (int)mmPerMin(p.retractionSpeed) << "\n";
                retracted = false;
            }
            ss << "G1 X" << pt.x << " Y" << pt.y
               << " F" << (int)mmPerMin(travelSpd) << "\n";
            curX = pt.x; curY = pt.y;
        };

        // Helper: retract
        auto doRetract = [&]() {
            if (!retracted) {
                E -= p.retractionLength;
                ss << "G1 E" << E << " F" << (int)mmPerMin(p.retractionSpeed) << "\n";
                retracted = true;
            }
        };

        // Helper: extrude along a loop (closed)
        auto extrudeLoop = [&](const Loop2& loop, float spd, float lh) {
            if (loop.size() < 2) return;
            float em = (filamentArea > 0.0f) ? (nozzleArea * lh / filamentArea) : 0.0f;
            travelTo(loop[0], p.travelSpeed);
            for (size_t i = 1; i <= loop.size(); ++i) {
                Vec2 pt = loop[i % loop.size()];
                float dx = pt.x - curX, dy = pt.y - curY;
                float segLen = std::sqrt(dx*dx + dy*dy);
                if (segLen < 1e-4f) continue;
                E += segLen * em;
                ss << "G1 X" << pt.x << " Y" << pt.y
                   << " E" << E << " F" << (int)mmPerMin(spd) << "\n";
                curX = pt.x; curY = pt.y;
            }
            doRetract();
        };

        // Helper: extrude along open paths
        auto extrudePaths = [&](const std::vector<Path2>& paths, float spd, float lh) {
            float em = (filamentArea > 0.0f) ? (nozzleArea * lh / filamentArea) : 0.0f;
            for (auto& path : paths) {
                if (path.size() < 2) continue;
                travelTo(path[0], p.travelSpeed);
                for (size_t i = 1; i < path.size(); ++i) {
                    Vec2 pt = path[i];
                    float dx = pt.x - curX, dy = pt.y - curY;
                    float segLen = std::sqrt(dx*dx + dy*dy);
                    if (segLen < 1e-4f) continue;
                    E += segLen * em;
                    ss << "G1 X" << pt.x << " Y" << pt.y
                       << " E" << E << " F" << (int)mmPerMin(spd) << "\n";
                    curX = pt.x; curY = pt.y;
                }
                doRetract();
            }
        };

        // ---- Layers ----
        for (auto& layer : result.layers) {
            float lh = (layer.index == 0) ? p.firstLayerHeight : p.layerHeight;

            if (layer.isRaftLayer) {
                // Raft layer
                bool isBase = (layer.index < p.raftBaseLayers);
                float raftSpd = isBase ? p.raftBaseSpeed : p.raftInterfaceSpeed;
                ss << "\n; --- Raft " << (isBase ? "Base" : "Interface")
                   << " Layer " << layer.index << " (z=" << std::setprecision(3) << layer.z << " mm) ---\n";
                if (std::abs(layer.z - curZ) > 1e-4f) {
                    ss << "G1 Z" << layer.z << " F" << (int)mmPerMin(5.0f) << "\n";
                    curZ = layer.z;
                }
                // Raft border (skirtLoops reused)
                if (!layer.skirtLoops.empty()) {
                    ss << "; Raft border\n";
                    for (auto& loop : layer.skirtLoops)
                        extrudeLoop(loop, raftSpd, lh);
                }
                ss << "; Raft fill\n";
                extrudePaths(layer.raftPaths, raftSpd, lh);
                continue;
            }

            float perimSpeed = (layer.index == 0) ? p.firstLayerSpeed : p.printSpeed;
            float infillSpd  = (layer.index == 0) ? p.firstLayerSpeed : p.infillSpeed;

            ss << "\n; --- Layer " << layer.index
               << " (z=" << std::setprecision(3) << layer.z << " mm) ---\n";

            if (std::abs(layer.z - curZ) > 1e-4f) {
                ss << "G1 Z" << layer.z << " F" << (int)mmPerMin(5.0f) << "\n";
                curZ = layer.z;
            }

            // ---- Skirt (first skirtLayers only) ----
            if (!layer.skirtLoops.empty()) {
                ss << "; Skirt\n";
                for (auto& loop : layer.skirtLoops)
                    extrudeLoop(loop, perimSpeed * 0.9f, lh);
            }

            // ---- Support ----
            if (!layer.supportPaths.empty()) {
                ss << "; Support\n";
                extrudePaths(layer.supportPaths, p.supportSpeed, lh);
            }

            // ---- Perimeter shells (inner → outer) ----
            for (int s = (int)layer.shells.size()-1; s >= 0; --s) {
                float spd = perimSpeed * (s == 0 ? 0.8f : 1.0f);
                ss << "; Shell " << s << "\n";
                for (auto& loop : layer.shells[s])
                    extrudeLoop(loop, spd, lh);
            }

            // ---- Solid fill ----
            if (!layer.solidPaths.empty()) {
                ss << "; Solid\n";
                extrudePaths(layer.solidPaths, infillSpd, lh);
            }

            // ---- Infill ----
            if (!layer.infillPaths.empty()) {
                ss << "; Infill\n";
                extrudePaths(layer.infillPaths, infillSpd, lh);
            }
        }

        // ---- End sequence ----
        ss << "\n; --- End of print ---\n";
        ss << "G1 Z" << (result.meshMax.z + 10.0f) << " F3000  ; Lift nozzle\n";
        ss << "G1 X0 Y" << (result.meshMax.y + 20.0f) << " F5000  ; Present print\n";
        ss << "M104 S0                ; Extruder off\n";
        ss << "M140 S0                ; Bed off\n";
        ss << "M84                    ; Motors off\n";
        ss << "; Total extrusion: " << std::setprecision(1) << E << " mm\n";

        return ss.str();
    }

    // Export to file
    static bool exportToFile(const SliceResult& result,
                              const std::string& filepath,
                              const std::string& printerName = "Generic FDM")
    {
        std::string gcode = exportToString(result, printerName);
        std::ofstream f(filepath);
        if (!f.is_open()) return false;
        f << gcode;
        return true;
    }

    // =========================================================================
    // GcodeMove — parsed move with semantic path type
    // pathType: 0=travel, 1=shell, 2=infill, 3=solid, 4=support, 5=skirt, 6=raft
    // =========================================================================
    struct GcodeMove {
        glm::vec3 from, to;
        float     extrusion;
        int       layerIdx;
        bool      isTravel;
        int       pathType;  // semantic feature type
    };

    // =========================================================================
    // Parse G-code string back into 3D move segments for visualization
    // =========================================================================
    static std::vector<GcodeMove> parseForVisualization(const std::string& gcode)
    {
        std::vector<GcodeMove> moves;
        moves.reserve(4096);

        float x = 0, y = 0, z = 0, e = 0;
        float prevX = 0, prevY = 0, prevZ = 0, prevE = 0;
        int   layerIdx = -1;
        float lastZ = -1.0f;
        int   curPathType = 1;  // default = shell

        std::istringstream ss(gcode);
        std::string line;
        while (std::getline(ss, line)) {
            if (line.empty()) continue;

            // Detect section comments for semantic type
            if (line[0] == ';') {
                if (line.find("Layer") != std::string::npos ||
                    line.find("Raft")  != std::string::npos) {
                    ++layerIdx;
                    curPathType = 1;  // reset to shell
                }
                // Semantic type detection from comments
                if      (line.find("; Skirt")   != std::string::npos) curPathType = 5;
                else if (line.find("; Support")  != std::string::npos) curPathType = 4;
                else if (line.find("; Shell")    != std::string::npos) curPathType = 1;
                else if (line.find("; Solid")    != std::string::npos) curPathType = 3;
                else if (line.find("; Infill")   != std::string::npos) curPathType = 2;
                else if (line.find("; Raft")     != std::string::npos) curPathType = 6;
                continue;
            }

            // Strip inline comments
            auto cpos = line.find(';');
            if (cpos != std::string::npos) line = line.substr(0, cpos);

            if (line.rfind("G1", 0) == 0 || line.rfind("G0", 0) == 0) {
                auto getVal = [&](char c) -> bool {
                    auto pos = line.find(c);
                    if (pos == std::string::npos) return false;
                    try {
                        float v = std::stof(line.substr(pos+1));
                        if      (c == 'X') x = v;
                        else if (c == 'Y') y = v;
                        else if (c == 'Z') z = v;
                        else if (c == 'E') e = v;
                    } catch(...) {}
                    return true;
                };
                getVal('X'); getVal('Y'); getVal('Z'); getVal('E');

                if (z != lastZ) { ++layerIdx; lastZ = z; }

                float dE = e - prevE;
                GcodeMove mv;
                mv.from     = glm::vec3(prevX, prevY, prevZ);
                mv.to       = glm::vec3(x, y, z);
                mv.extrusion= dE;
                mv.layerIdx = std::max(0, layerIdx);
                mv.isTravel = (dE <= 0.0f);
                mv.pathType = mv.isTravel ? 0 : curPathType;

                if (glm::distance(mv.from, mv.to) > 1e-4f)
                    moves.push_back(mv);

                prevX = x; prevY = y; prevZ = z; prevE = e;
            } else if (line.rfind("G92", 0) == 0) {
                auto pos = line.find('E');
                if (pos != std::string::npos) {
                    try { e = std::stof(line.substr(pos+1)); prevE = e; } catch(...) {}
                }
            }
        }
        return moves;
    }
};
