#pragma once
// =============================================================================
// GcodeExporter.h  —  FDM G-code Generator  (BambuStudio-inspired)
// =============================================================================
//
// Improvements over previous version (reference: BambuStudio GCode.cpp):
//
//  1. G2/G3 arc output
//     Uses SlicerEngine::fitArcs() to replace polyline segments with arc
//     commands, reducing G-code file size by 30-60% for curved geometries.
//     Matches BambuStudio's ArcFitter integration in GCode.cpp.
//
//  2. Smart retraction
//     Skips retraction for short travels (< minTravelForRetract mm),
//     matching BambuStudio's retraction avoidance strategy.
//
//  3. Speed zones (BambuStudio-style feature speeds)
//     Outer perimeter:  outerPerimSpeed  (slower for surface quality)
//     Inner perimeter:  innerPerimSpeed
//     Bridge:           bridgeSpeed      (slower for bridging)
//     Support interface: supportSpeed × 0.8
//
//  4. Bridge fill output
//     Emits bridge paths with fan speed override (M106 S255) and reduced
//     speed, matching BambuStudio's bridge handling.
//
//  5. Support interface layer
//     Emits supportInterfacePaths as a separate section with denser fill
//     and slower speed for better surface quality.
//
//  6. Print order (BambuStudio default):
//     Skirt → Support → Support Interface → Inner Shells → Outer Shell →
//     Solid/Bridge Fill → Infill
//
//  7. Semantic pathType extended:
//     0=travel, 1=outer_shell, 2=infill, 3=solid, 4=support,
//     5=skirt, 6=raft, 7=bridge, 8=support_interface, 9=inner_shell
//
// =============================================================================

#include "SlicerEngine.h"
#include <sstream>
#include <fstream>
#include <iomanip>
#include <cmath>

class GcodeExporter {
public:
    // =========================================================================
    // Export to string
    // =========================================================================
    static std::string exportToString(const SliceResult& result,
                                       const std::string& printerName = "Generic FDM")
    {
        if (!result.success || result.layers.empty())
            return "; Empty slice result\n";

        std::ostringstream ss;
        ss << std::fixed << std::setprecision(4);

        const SlicerParams& p = result.params;

        // ---- Header ----
        ss << "; Generated by MCUT Boolean Viewer — Slicer Module\n";
        ss << "; Printer     : " << printerName << "\n";
        ss << "; Layers      : " << result.layers.size() << "\n";
        ss << "; Layer H     : " << p.layerHeight << " mm\n";
        ss << "; Nozzle      : " << p.nozzleDiameter << " mm\n";
        ss << "; Extrusion W : " << p.extrusionWidth << " mm (outer: " << p.outerExtrusionWidth << " mm)\n";
        ss << "; Infill      : " << (int)(p.infillDensity * 100) << "%";
        if (p.useGyroid)    ss << " (gyroid)";
        else if (p.useHoneycomb) ss << " (honeycomb)";
        else                ss << " (rectilinear ±45°)";
        ss << "\n";
        ss << "; Shells      : " << p.numShells << "\n";
        ss << "; Skirt       : " << (p.enableSkirt ? std::to_string(p.skirtLoopCount) + " loops" : "disabled") << "\n";
        ss << "; Raft        : " << (p.enableRaft  ? std::to_string(p.raftBaseLayers + p.raftInterfaceLayers) + " layers" : "disabled") << "\n";
        ss << "; Support     : " << (p.enableSupport ? std::to_string((int)p.supportAngle) + "° threshold" + (p.supportInterface ? " + interface" : "") : "disabled") << "\n";
        ss << "; Arc fitting : " << (p.enableArcFitting ? "enabled (tol=" + std::to_string(p.arcTolerance) + "mm)" : "disabled") << "\n";
        ss << "; Filament    : " << std::setprecision(1) << result.estimatedFilament << " mm\n";
        ss << "; Est.Time    : " << (int)(result.estimatedTime/60) << "m "
                                  << (int)result.estimatedTime%60 << "s\n";
        ss << ";\n";

        // ---- Startup sequence ----
        ss << "G28                    ; Home all axes\n";
        ss << "G90                    ; Absolute positioning\n";
        ss << "M82                    ; Absolute extrusion\n";
        ss << "M104 S" << (int)p.extruderTemp << "           ; Set extruder temp\n";
        ss << "M140 S" << (int)p.bedTemp      << "            ; Set bed temp\n";
        ss << "M109 S" << (int)p.extruderTemp << "           ; Wait for extruder\n";
        ss << "M190 S" << (int)p.bedTemp      << "            ; Wait for bed\n";
        ss << "M106 S0                ; Fan off initially\n";
        ss << "G92 E0                 ; Reset extruder\n";
        ss << "; --- Purge line ---\n";
        ss << "G1 Z0.3 F3000\n";
        ss << "G1 X10 Y10 F5000\n";
        ss << "G1 X100 Y10 E10 F1500\n";
        ss << "G92 E0\n";
        ss << ";\n";

        // Extrusion multiplier
        float nozzleArea   = (float)M_PI * (p.nozzleDiameter  * 0.5f) * (p.nozzleDiameter  * 0.5f);
        float filamentArea = (float)M_PI * (p.filamentDiameter * 0.5f) * (p.filamentDiameter * 0.5f);

        float E = 0.0f;
        float curX = 0.0f, curY = 0.0f, curZ = -999.0f;
        bool  retracted = false;
        bool  fanOn     = false;
        int   fanLayer  = 3;  // enable fan after layer 3 (BambuStudio default)

        auto mmPerMin = [](float mmPerSec) { return mmPerSec * 60.0f; };

        // Compute extrusion per mm for a given layer height and width
        auto extPerMm = [&](float lh, float ew) -> float {
            if (filamentArea < 1e-8f) return 0.0f;
            return (ew * lh) / filamentArea;
        };

        // Travel with smart retraction (skip retraction for short moves)
        auto travelTo = [&](Vec2 pt, float travelSpd) {
            float dist = std::sqrt((pt.x-curX)*(pt.x-curX) + (pt.y-curY)*(pt.y-curY));
            if (dist < 1e-4f) return;

            if (retracted) {
                // Un-retract
                E += p.retractionLength;
                ss << "G1 E" << E << " F" << (int)mmPerMin(p.retractionSpeed) << "\n";
                retracted = false;
            }
            ss << "G0 X" << pt.x << " Y" << pt.y
               << " F" << (int)mmPerMin(travelSpd) << "\n";
            curX = pt.x; curY = pt.y;
        };

        auto doRetract = [&](float travelDist = 999.0f) {
            if (!retracted && travelDist >= p.minTravelForRetract) {
                E -= p.retractionLength;
                ss << "G1 E" << E << " F" << (int)mmPerMin(p.retractionSpeed) << "\n";
                retracted = true;
            }
        };

        // Extrude a loop (closed polygon) — with optional arc fitting
        auto extrudeLoop = [&](const Loop2& loop, float spd, float lh, float ew, int pathType) {
            if (loop.size() < 2) return;
            float em = extPerMm(lh, ew);

            // Compute next start point distance for retraction decision
            float travelDist = std::sqrt((loop[0].x-curX)*(loop[0].x-curX) +
                                          (loop[0].y-curY)*(loop[0].y-curY));
            if (travelDist >= p.minTravelForRetract) doRetract(travelDist);
            travelTo(loop[0], p.travelSpeed);

            // Build path for arc fitting
            Path2 fullPath;
            fullPath.reserve(loop.size() + 1);
            for (auto& pt : loop) fullPath.push_back(pt);
            fullPath.push_back(loop[0]);  // close loop

            emitPathWithArcs(ss, fullPath, em, spd, E, curX, curY, p, mmPerMin, pathType);
            doRetract();
        };

        // Extrude open paths — with optional arc fitting
        auto extrudePaths = [&](const std::vector<Path2>& paths, float spd, float lh, float ew, int pathType) {
            float em = extPerMm(lh, ew);
            for (auto& path : paths) {
                if (path.size() < 2) continue;
                float travelDist = std::sqrt((path[0].x-curX)*(path[0].x-curX) +
                                              (path[0].y-curY)*(path[0].y-curY));
                if (travelDist >= p.minTravelForRetract) doRetract(travelDist);
                travelTo(path[0], p.travelSpeed);
                emitPathWithArcs(ss, path, em, spd, E, curX, curY, p, mmPerMin, pathType);
                doRetract();
            }
        };

        // ---- Layers ----
        for (auto& layer : result.layers) {
            float lh = (layer.index == 0) ? p.firstLayerHeight : p.layerHeight;

            // Fan control (BambuStudio enables fan after layer 3)
            if (!fanOn && layer.index >= fanLayer && !layer.isRaftLayer) {
                ss << "M106 S255              ; Fan on\n";
                fanOn = true;
            }

            if (layer.isRaftLayer) {
                bool isBase = (layer.index < p.raftBaseLayers);
                float raftSpd = isBase ? p.raftBaseSpeed : p.raftInterfaceSpeed;
                ss << "\n; --- Raft " << (isBase ? "Base" : "Interface")
                   << " Layer " << layer.index << " (z=" << std::setprecision(3) << layer.z << " mm) ---\n";
                if (std::abs(layer.z - curZ) > 1e-4f) {
                    ss << "G1 Z" << layer.z << " F" << (int)mmPerMin(5.0f) << "\n";
                    curZ = layer.z;
                }
                if (!layer.skirtLoops.empty()) {
                    ss << "; Raft border\n";
                    for (auto& loop : layer.skirtLoops)
                        extrudeLoop(loop, raftSpd, lh, p.extrusionWidth * 1.5f, 6);
                }
                ss << "; Raft fill\n";
                extrudePaths(layer.raftPaths, raftSpd, lh, p.extrusionWidth * 1.5f, 6);
                continue;
            }

            float firstLayerMult = (layer.index == 0) ? 0.5f : 1.0f;  // slower first layer
            float outerSpd = (layer.index == 0) ? p.firstLayerSpeed : p.outerPerimSpeed;
            float innerSpd = (layer.index == 0) ? p.firstLayerSpeed : p.innerPerimSpeed;
            float infillSpd= (layer.index == 0) ? p.firstLayerSpeed : p.infillSpeed;

            ss << "\n; --- Layer " << layer.index
               << " (z=" << std::setprecision(3) << layer.z << " mm) ---\n";

            if (std::abs(layer.z - curZ) > 1e-4f) {
                ss << "G1 Z" << layer.z << " F" << (int)mmPerMin(5.0f) << "\n";
                curZ = layer.z;
            }

            // Print order: Skirt → Support → Support Interface →
            //              Inner Shells → Outer Shell → Solid/Bridge → Infill

            // 1. Skirt
            if (!layer.skirtLoops.empty()) {
                ss << "; Skirt\n";
                for (auto& loop : layer.skirtLoops)
                    extrudeLoop(loop, outerSpd * 0.9f, lh, p.extrusionWidth, 5);
            }

            // 2. Support
            if (!layer.supportPaths.empty()) {
                ss << "; Support\n";
                extrudePaths(layer.supportPaths, p.supportSpeed, lh, p.extrusionWidth, 4);
            }

            // 3. Support interface (dense, slow)
            if (!layer.supportInterfacePaths.empty()) {
                ss << "; Support Interface\n";
                extrudePaths(layer.supportInterfacePaths, p.supportSpeed * 0.8f, lh,
                             p.extrusionWidth * 0.9f, 8);
            }

            // 4. Inner shells (inner → outer, BambuStudio default)
            for (int s = (int)layer.shells.size()-1; s >= 1; --s) {
                ss << "; Inner Shell " << s << "\n";
                for (auto& loop : layer.shells[s])
                    extrudeLoop(loop, innerSpd, lh, p.extrusionWidth, 9);
            }

            // 5. Outer shell (last, for best surface quality)
            if (!layer.shells.empty()) {
                ss << "; Outer Shell\n";
                for (auto& loop : layer.shells[0])
                    extrudeLoop(loop, outerSpd, lh, p.outerExtrusionWidth, 1);
            }

            // 6. Solid fill
            if (!layer.solidPaths.empty()) {
                ss << "; Solid\n";
                extrudePaths(layer.solidPaths, infillSpd, lh, p.extrusionWidth, 3);
            }

            // 7. Bridge fill (with fan boost)
            if (!layer.bridgePaths.empty()) {
                ss << "M106 S255              ; Bridge fan boost\n";
                ss << "; Bridge\n";
                extrudePaths(layer.bridgePaths, p.bridgeSpeed, lh, p.extrusionWidth * 1.1f, 7);
                if (fanOn) ss << "M106 S255              ; Restore fan\n";
                else       ss << "M106 S0                ; Fan off\n";
            }

            // 8. Infill
            if (!layer.infillPaths.empty()) {
                ss << "; Infill\n";
                extrudePaths(layer.infillPaths, infillSpd, lh, p.extrusionWidth, 2);
            }
        }

        // ---- End sequence ----
        ss << "\n; --- End of print ---\n";
        ss << "G1 Z" << (result.meshMax.z + 10.0f) << " F3000  ; Lift nozzle\n";
        ss << "G1 X0 Y" << (result.meshMax.y + 20.0f) << " F5000  ; Present print\n";
        ss << "M106 S0                ; Fan off\n";
        ss << "M104 S0                ; Extruder off\n";
        ss << "M140 S0                ; Bed off\n";
        ss << "M84                    ; Motors off\n";
        ss << "; Total extrusion: " << std::setprecision(1) << E << " mm\n";

        return ss.str();
    }

    // Export to file
    static bool exportToFile(const SliceResult& result,
                              const std::string& filepath,
                              const std::string& printerName = "Generic FDM")
    {
        std::string gcode = exportToString(result, printerName);
        std::ofstream f(filepath);
        if (!f.is_open()) return false;
        f << gcode;
        return true;
    }

    // =========================================================================
    // GcodeMove — parsed move with semantic path type
    // pathType: 0=travel, 1=outer_shell, 2=infill, 3=solid, 4=support,
    //           5=skirt, 6=raft, 7=bridge, 8=support_interface, 9=inner_shell
    // =========================================================================
    struct GcodeMove {
        glm::vec3 from, to;
        float     extrusion;
        int       layerIdx;
        bool      isTravel;
        int       pathType;
        bool      isArc;       // true if this move came from G2/G3
        Vec2      arcCenter;   // arc center (I, J offsets resolved)
        bool      arcCCW;      // G3 = true, G2 = false
    };

    // =========================================================================
    // Parse G-code back into 3D moves for visualization
    // Now handles G2/G3 arc commands.
    // =========================================================================
    static std::vector<GcodeMove> parseForVisualization(const std::string& gcode)
    {
        std::vector<GcodeMove> moves;
        moves.reserve(8192);

        float x = 0, y = 0, z = 0, e = 0;
        float prevX = 0, prevY = 0, prevZ = 0, prevE = 0;
        int   layerIdx = -1;
        float lastZ = -1.0f;
        int   curPathType = 1;

        std::istringstream ss(gcode);
        std::string line;
        while (std::getline(ss, line)) {
            if (line.empty()) continue;

            if (line[0] == ';') {
                if (line.find("Layer") != std::string::npos ||
                    line.find("Raft")  != std::string::npos) {
                    ++layerIdx; curPathType = 1;
                }
                if      (line.find("; Skirt")             != std::string::npos) curPathType = 5;
                else if (line.find("; Support Interface")  != std::string::npos) curPathType = 8;
                else if (line.find("; Support")            != std::string::npos) curPathType = 4;
                else if (line.find("; Outer Shell")        != std::string::npos) curPathType = 1;
                else if (line.find("; Inner Shell")        != std::string::npos) curPathType = 9;
                else if (line.find("; Shell")              != std::string::npos) curPathType = 1;
                else if (line.find("; Solid")              != std::string::npos) curPathType = 3;
                else if (line.find("; Bridge")             != std::string::npos) curPathType = 7;
                else if (line.find("; Infill")             != std::string::npos) curPathType = 2;
                else if (line.find("; Raft")               != std::string::npos) curPathType = 6;
                continue;
            }

            auto cpos = line.find(';');
            if (cpos != std::string::npos) line = line.substr(0, cpos);

            // Parse G0/G1 linear moves
            if (line.rfind("G1", 0) == 0 || line.rfind("G0", 0) == 0) {
                auto getVal = [&](char c) {
                    auto pos = line.find(c);
                    if (pos == std::string::npos) return;
                    try {
                        float v = std::stof(line.substr(pos+1));
                        if      (c == 'X') x = v;
                        else if (c == 'Y') y = v;
                        else if (c == 'Z') z = v;
                        else if (c == 'E') e = v;
                    } catch(...) {}
                };
                getVal('X'); getVal('Y'); getVal('Z'); getVal('E');
                if (z != lastZ) { ++layerIdx; lastZ = z; }

                float dE = e - prevE;
                GcodeMove mv;
                mv.from      = glm::vec3(prevX, prevY, prevZ);
                mv.to        = glm::vec3(x, y, z);
                mv.extrusion = dE;
                mv.layerIdx  = std::max(0, layerIdx);
                mv.isTravel  = (dE <= 0.0f);
                mv.pathType  = mv.isTravel ? 0 : curPathType;
                mv.isArc     = false;
                mv.arcCCW    = false;

                if (glm::distance(mv.from, mv.to) > 1e-4f) moves.push_back(mv);
                prevX = x; prevY = y; prevZ = z; prevE = e;
            }
            // Parse G2/G3 arc moves — tessellate into line segments for visualization
            else if (line.rfind("G2", 0) == 0 || line.rfind("G3", 0) == 0) {
                bool ccw = (line[1] == '3');
                float ex = x, ey = y;
                float I = 0, J = 0;
                auto getVal2 = [&](char c) {
                    auto pos = line.find(c);
                    if (pos == std::string::npos) return;
                    try {
                        float v = std::stof(line.substr(pos+1));
                        if      (c == 'X') ex = v;
                        else if (c == 'Y') ey = v;
                        else if (c == 'I') I  = v;
                        else if (c == 'J') J  = v;
                        else if (c == 'E') e  = v;
                    } catch(...) {}
                };
                getVal2('X'); getVal2('Y'); getVal2('I'); getVal2('J'); getVal2('E');

                // Tessellate arc into segments
                float cx = x + I, cy = y + J;
                float r  = std::sqrt(I*I + J*J);
                float startA = std::atan2(y - cy, x - cx);
                float endA   = std::atan2(ey - cy, ex - cx);
                float dA = endA - startA;
                if (ccw && dA < 0) dA += 2*(float)M_PI;
                if (!ccw && dA > 0) dA -= 2*(float)M_PI;

                int segs = std::max(4, (int)(std::abs(r * dA) / 0.5f));
                float dE = e - prevE;
                float dePerSeg = dE / segs;

                for (int si = 1; si <= segs; ++si) {
                    float a = startA + dA * si / segs;
                    float nx = cx + r * std::cos(a);
                    float ny = cy + r * std::sin(a);

                    GcodeMove mv;
                    mv.from      = glm::vec3(prevX, prevY, prevZ);
                    mv.to        = glm::vec3(nx, ny, z);
                    mv.extrusion = dePerSeg;
                    mv.layerIdx  = std::max(0, layerIdx);
                    mv.isTravel  = (dE <= 0.0f);
                    mv.pathType  = mv.isTravel ? 0 : curPathType;
                    mv.isArc     = true;
                    mv.arcCenter = Vec2(cx, cy);
                    mv.arcCCW    = ccw;

                    if (glm::distance(mv.from, mv.to) > 1e-4f) moves.push_back(mv);
                    prevX = nx; prevY = ny;
                }
                x = ex; y = ey; prevE = e;
            }
            else if (line.rfind("G92", 0) == 0) {
                auto pos = line.find('E');
                if (pos != std::string::npos) {
                    try { e = std::stof(line.substr(pos+1)); prevE = e; } catch(...) {}
                }
            }
        }
        return moves;
    }

private:
    // =========================================================================
    // Emit a path with optional G2/G3 arc fitting
    // BambuStudio: ArcFitter::do_arc_fitting_and_simplify() is called on each
    // polyline before G-code emission.
    // =========================================================================
    static void emitPathWithArcs(
        std::ostringstream& ss,
        const Path2& path,
        float em,
        float spd,
        float& E,
        float& curX,
        float& curY,
        const SlicerParams& p,
        std::function<float(float)> mmPerMin,
        int /*pathType*/)
    {
        if (path.size() < 2) return;

        // Fit arcs
        std::vector<ArcSegment> arcs = SlicerEngine::fitArcs(path, p);

        // Build a set of arc-covered index ranges
        // For points not covered by arcs, emit G1; for arc ranges, emit G2/G3
        size_t n = path.size();
        size_t i = 0;

        // Build arc index map: arcMap[startIdx] = arc
        std::unordered_map<int, const ArcSegment*> arcMap;
        for (auto& arc : arcs) arcMap[arc.startIdx] = &arc;

        while (i < n - 1) {
            auto it = arcMap.find((int)i);
            if (it != arcMap.end()) {
                const ArcSegment& arc = *it->second;
                // Emit G2/G3
                Vec2 endPt = path[arc.endIdx];
                float I = arc.center.x - curX;
                float J = arc.center.y - curY;

                // Compute arc length for extrusion
                float dA = arc.endAngle - arc.startAngle;
                if (arc.ccw && dA < 0) dA += 2*(float)M_PI;
                if (!arc.ccw && dA > 0) dA -= 2*(float)M_PI;
                float arcLen = std::abs(arc.radius * dA);
                E += arcLen * em;

                ss << (arc.ccw ? "G3" : "G2")
                   << " X" << endPt.x << " Y" << endPt.y
                   << " I" << I << " J" << J
                   << " E" << E
                   << " F" << (int)mmPerMin(spd) << "\n";

                curX = endPt.x; curY = endPt.y;
                i = arc.endIdx;
            } else {
                // Emit G1
                Vec2 pt = path[i+1];
                float dx = pt.x - curX, dy = pt.y - curY;
                float segLen = std::sqrt(dx*dx + dy*dy);
                if (segLen > 1e-4f) {
                    E += segLen * em;
                    ss << "G1 X" << pt.x << " Y" << pt.y
                       << " E" << E << " F" << (int)mmPerMin(spd) << "\n";
                    curX = pt.x; curY = pt.y;
                }
                ++i;
            }
        }
    }
};
